---
- name: CI/CD pipeline inside single EC2 (Jenkins, Docker, Terraform, Ansible all-in-one)
  hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Build Docker image for LUGX site
      docker_image:
        name: lugx-site
        path: .
        state: present

    - name: Run Docker container from built image
      docker_container:
        name: lugx-container
        image: lugx-site
        state: started
        ports:
          - "82:80"
        restart_policy: always

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: ./terraform

    - name: Validate Terraform files
      command: terraform validate
      args:
        chdir: ./terraform

    - name: Plan Terraform deployment
      command: terraform plan -out=tfplan
      args:
        chdir: ./terraform

    - name: Apply Terraform plan
      command: terraform apply -auto-approve tfplan
      args:
        chdir: ./terraform
